plugins {
    id 'com.android.application'
}

android {
    namespace 'com.dadi.privatkomisi'
    compileSdk 35

    defaultConfig {
        applicationId 'com.dadihardadi.privatkomisi.stable'
        minSdk 21
        targetSdk 35
        versionCode 7
        versionName '7.0'
    }

    signingConfigs {
        release {
            storeFile file('privatkomisi.keystore')
            storePassword 'PrivatKomisi2026'
            keyAlias 'privatkomisi'
            keyPassword 'PrivatKomisi2026'
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.release
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
